#!/usr/bin/env bash
#setting up nginx
sudo apt update
sudo apt-get -y install nginx
sudo apt-get -y install ufw
sudo ufw --force enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
echo "Hello World!" > somepage.html
sudo cp somepage.html /var/www/html/index.html
