#!/usr/bin/env bash
#fizzbuzz
x=1
f=1
b=1
fb=1
while [ $x -lt 101 ]
do
        f=$(( x % 3))
        b=$(( x % 5))
        fb=$(( x % 15))
        if [ "$fb" -eq 0 ]
        then
                echo "FizzBuzz"
        elif [ "$f" -eq 0 ]
        then
                echo "Fizz"
        elif [ "$b" -eq 0 ]
        then
                echo "Buzz"
        else
                echo $x
        fi
        x=$(( x + 1))
done