#!/usr/bin/env bash
#displays Best School 10 times. Hi at 9
x=0
while [ $x -lt 10 ]
do
        if [ "$x" -ne 8 ]
        then
                echo "Best School"
        else
                echo "Best School"
                echo "Hi"
        fi
        x=$(( x + 1))
done
