#!/usr/bin/env bash
# displays hours and minutes
h=0
min=1
while [ $h -lt 13 ]
do
        echo "Hour: $h"
        min=$(( 1 ))
        while [ $min -lt 60 ]
        do
                echo $min
                min=$(( min + 1))
        done
        h=$(( h + 1))
done